In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("datasets/housing.csv")

In [ ]:
data

In [ ]:
data.info()

In [ ]:
data.dropna(inplace=True)
data.info()

In [ ]:
from sklearn.model_selection import train_test_split

X = data.drop(["median_house_value"], axis=1)
y = data["median_house_value"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
train_data = X_train.join(y_train)

In [ ]:
train_data

In [ ]:
train_data.hist(figsize=(15,15))

In [ ]:
train_data.corr(numeric_only=True)

In [ ]:
plt.figure(figsize=(15, 8))
sns.heatmap(train_data.corr(numeric_only=True), annot=True)

In [ ]:
train_data["total_rooms"] = np.log(train_data["total_rooms"] + 1)
train_data["total_bedrooms"] = np.log(train_data["total_bedrooms"] + 1)
train_data["population"] = np.log(train_data["population"] + 1)
train_data["households"] = np.log(train_data["households"] + 1)

In [ ]:
train_data.hist(figsize=(15, 15))

In [ ]:
train_data.ocean_proximity.value_counts()

In [ ]:
train_data = train_data.join(pd.get_dummies(train_data.ocean_proximity)).drop(["ocean_proximity"], axis=1)

In [ ]:
plt.figure(figsize=(15, 8))
sns.heatmap(train_data.corr(numeric_only=True), annot=True)

In [ ]:
plt.figure(figsize=(15, 8))
sns.scatterplot(x="latitude", y="longitude", data=train_data, hue="median_house_value")

In [ ]:
train_data["bedroom_ratio"] = train_data["total_bedrooms"] / train_data["total_rooms"]
train_data["household_rooms"] = train_data["total_rooms"] / train_data["households"]

In [ ]:
plt.figure(figsize=(15, 8))
sns.heatmap(train_data.corr(numeric_only=True), annot=True)

In [75]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()


X_train, y_train = train_data.drop(["median_house_value"], axis=1), train_data["median_house_value"]
X_train_s = scaler.fit_transform(X_train)    

reg = LinearRegression()

reg.fit(X_train_s, y_train)

LinearRegression()

In [ ]:
test_data = X_test.join(y_test)

test_data['total_rooms'] = np.log(test_data['total_rooms'] + 1)
test_data['total_bedrooms'] = np.log(test_data['total_bedrooms'] + 1)
test_data['population'] = np.log(test_data['population'] + 1)
test_data['households'] = np.log(test_data['households'] + 1)

test_data = test_data.join(pd.get_dummies(test_data.ocean_proximity)).drop(['ocean_proximity'], axis=1)

test_data['bedroom_ratio'] = test_data['total_bedrooms'] / test_data['total_rooms']
test_data['household_rooms'] = test_data['total_rooms'] / test_data['households']

In [76]:

X_test, y_test = test_data.drop(["median_house_value"], axis=1), test_data["median_house_value"]

In [77]:
X_test_s = scaler.fit_transform(X_test)

In [78]:
train_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN,bedroom_ratio,household_rooms
8363,-118.35,33.97,33.0,7.310550,6.163315,7.149132,6.104793,2.0694,143500.0,True,False,False,False,False,0.843071,1.197510
1391,-122.10,37.97,18.0,8.372630,6.486161,7.469654,6.472346,5.6931,269600.0,False,False,False,True,False,0.774686,1.293600
19552,-120.99,37.63,21.0,5.768321,4.795791,5.624018,4.454347,2.4792,60000.0,False,True,False,False,False,0.831401,1.294987
9541,-120.74,37.33,30.0,7.779467,6.154858,7.251345,6.061457,2.1484,81300.0,False,True,False,False,False,0.791167,1.283432
1793,-122.42,37.93,47.0,8.147288,6.659294,7.210818,6.591674,4.0160,274500.0,False,False,False,True,False,0.817363,1.235997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15418,-117.25,33.22,26.0,7.606387,5.852202,7.057037,5.805135,3.9815,142600.0,True,False,False,False,False,0.769380,1.310286
12194,-117.29,33.63,7.0,9.681031,7.910957,8.873468,7.794411,3.8056,162200.0,True,False,False,False,False,0.817161,1.242048
14368,-117.24,32.73,37.0,7.723562,5.872118,6.697034,5.863631,5.9113,388300.0,False,False,False,False,True,0.760286,1.317198
9867,-121.84,36.61,26.0,7.973500,6.635947,7.722678,6.579251,2.5663,128900.0,True,False,False,False,False,0.832250,1.211916
1559,-121.97,37.79,16.0,8.262043,6.184149,7.280697,6.218600,6.7857,341300.0,True,False,False,False,False,0.748501,1.328602

In [79]:
train_data, test_data = train_data.align(test_data, join='left', axis=1, fill_value=False)
test_data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN,bedroom_ratio,household_rooms
10132,-117.91,33.91,27.0,2.161942,1.976661,2.122246,1.973020,3.6106,196400.0,True,False,False,False,False,0.808871,1.241529
15804,-122.44,37.76,50.0,2.181481,1.994106,2.060799,1.987982,5.2519,376600.0,False,False,False,True,False,0.807393,1.247370
17828,-121.86,37.40,16.0,2.172463,1.933476,2.111232,1.935031,5.8721,267800.0,True,False,False,False,False,0.760102,1.313226
10863,-117.88,33.71,27.0,2.125356,1.901674,2.133069,1.897602,4.1000,184900.0,True,False,False,False,False,0.772395,1.300888
11103,-117.88,33.85,34.0,2.082961,1.828693,1.998560,1.825195,4.3750,224700.0,True,False,False,False,False,0.743540,1.350537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17284,-119.74,34.41,30.0,2.171218,1.950966,2.074473,1.948216,5.5959,346200.0,False,False,False,False,True,0.776872,1.291349
12203,-117.12,33.61,2.0,2.180605,1.955638,2.093986,1.940694,4.3651,145600.0,True,False,False,False,False,0.772884,1.316602
15251,-117.27,32.98,17.0,2.143015,1.942162,1.926237,1.847247,5.2742,230700.0,False,False,False,False,True,0.793851,1.408579
4960,-118.30,34.00,52.0,2.135814,1.952319,2.091357,1.939208,1.6875,116000.0,True,False,False,False,False,0.809895,1.253760
9174,-118.52,34.39,21.0,2.262648,2.098200,2.211249,2.092982,3.6625,228100.0,True,False,False,False,False,0.830747,1.210919

In [81]:
reg.score(X_test_s, y_test)

0.663477789880099